<?php

namespace inquid\vue\classes;


interface VueArrayContract
{
    /**
     * This method returns the array generated by the class.
     *
     * eg. data();
     *
     * @return array the final result of the class.
     */
    public function getArray(): array;
}
